export const FETCH_QUIZZES = 'FETCH_QUIZZES';
export const FETCH_QUIZ = 'FETCH_QUIZ';
export const CREATE_QUIZ = 'CREATE_QUIZ';
export const DELETE_QUIZ = 'DELETE_QUIZ';
export const EDIT_QUIZ = 'EDIT_QUIZ';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const EDIT_CATEGORY   = 'EDIT_CATEGORY';

export const FETCH_IMAGES = 'FETCH_IMAGES';
export const FETCH_IMAGE = 'FETCH_IMAGE';
export const CREATE_IMAGE = 'CREATE_IMAGE';
export const EDIT_IMAGE = 'EDIT_IMAGE';
export const DELETE_IMAGE = 'DELETE_IMAGE';

export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const FETCH_QUESTION = 'FETCH_QUESTION';
export const CREATE_QUESTION = 'CREATE_QUESTION';
export const EDIT_QUESTION = 'EDIT_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';